insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (1, 'KMZ', 'Indonesia', 'ZM-01', 'Sumberagung', '10/17/2020', '3/28/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (2, 'NTU', 'Peru', 'US-VA', 'Santo Tomas', '11/30/2023', '6/24/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (3, 'GVA', 'Netherlands', 'CH-GE', 'Bergen op Zoom', '7/30/2023', '4/6/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (4, 'YAB', 'Ukraine', 'CA-NU', 'Nuyno', '4/16/2022', '1/13/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (5, 'ZKP', 'Russia', 'RU-SA', 'Lukhovka', '12/30/2020', '3/21/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (6, 'GZW', 'Portugal', 'IR-28', 'Vermoim', '4/1/2021', '3/30/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (7, 'IRN', 'Portugal', 'HN-CL', 'Pontes', '3/2/2021', '7/17/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (8, 'HZG', 'Honduras', 'CN-61', 'Guanaja', '1/12/2021', '7/15/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (9, 'AAH', 'Indonesia', 'DE-NW', 'Dajalorong', '1/19/2024', '10/4/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (10, 'GAV', 'China', 'ID-PB', 'Lanlongkou', '9/28/2023', '5/13/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (11, 'ALY', 'China', 'EG-ALX', 'Jintang', '1/22/2024', '10/4/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (12, 'YXT', 'China', 'CA-BC', 'Hongxing', '5/24/2022', '4/8/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (13, 'IOP', 'Lebanon', 'PG-NPP', 'Sidon', '5/16/2023', '10/27/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (14, 'OJC', 'Japan', 'US-KS', 'Ninomiya', '6/17/2021', '6/26/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (15, 'TTX', 'Indonesia', 'AU-WA', 'Mekarsari', '2/28/2023', '11/7/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (16, 'GCT', 'Ukraine', 'US-AZ', 'Staryy Dobrotvir', '4/27/2021', '9/18/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (17, 'BBQ', 'Philippines', 'AG-10', 'Sugcad', '6/20/2020', '4/1/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (18, 'YKH', 'Poland', 'CN-21', 'Czerwionka-Leszczyny', '11/24/2024', '3/25/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (19, 'CVC', 'Philippines', 'AU-SA', 'Rajal Norte', '6/21/2021', '5/24/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (20, 'KKC', 'China', 'TH-40', 'Xianan', '1/12/2024', '8/9/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (21, 'VDY', 'Argentina', 'IN-KA', 'El Colorado', '5/28/2023', '1/7/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (22, 'CFS', 'Portugal', 'AU-NSW', 'Alvito de São Pedro', '3/10/2024', '7/22/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (23, 'AME', 'Thailand', 'MZ-Q', 'Phayao', '7/26/2020', '1/29/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (24, 'VAU', 'Colombia', 'FJ-W', 'Cimitarra', '4/4/2023', '5/9/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (25, 'OCM', 'Brazil', 'AU-WA', 'Irecê', '9/15/2024', '12/9/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (26, 'ZKE', 'Philippines', 'CA-ON', 'Ramos West', '2/15/2022', '9/11/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (27, 'KOD', 'Russia', 'ID-KI', 'Lyudinovo', '8/22/2022', '7/29/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (28, 'SVX', 'Nigeria', 'RU-SVE', 'Yanda Bayo', '2/1/2021', '8/5/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (29, 'PCJ', 'Indonesia', 'PY-1', 'Banjar Paangkelod', '10/21/2021', '2/18/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (30, '0', 'Peru', 'BR-SP', 'Curpahuasi', '9/6/2022', '10/12/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (31, 'DBT', 'Greece', 'ET-AM', 'Plomárion', '10/3/2021', '6/22/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (32, 'YHN', 'Thailand', 'CA-ON', 'Nam Kliang', '7/11/2021', '8/10/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (33, 'PCD', 'Indonesia', 'US-WI', 'Ngedhusuba', '3/11/2023', '6/9/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (34, 'IBA', 'Pakistan', 'NG-OY', 'Mānānwāla', '6/7/2020', '10/26/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (35, 'CLL', 'China', 'US-TX', 'Shuangchahe', '12/25/2021', '4/12/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (36, 'BOU', 'Czech Republic', 'FR-F', 'Mirotice', '10/9/2020', '5/17/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (37, 'URO', 'Brazil', 'FR-Q', 'Abaeté', '1/24/2021', '9/22/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (38, 'FYV', 'Portugal', 'US-AR', 'São Miguel', '9/17/2021', '1/15/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (39, 'RFN', 'Poland', 'IS-6', 'Żelazków', '4/28/2023', '9/9/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (40, 'ASC', 'China', 'BO-S', 'Yangjingziwan', '7/18/2022', '12/15/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (41, 'ZWL', 'China', 'CA-SK', 'Heilangkou', '4/15/2024', '11/23/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (42, 'BWC', 'Honduras', 'US-CA', 'El Lolo', '2/14/2022', '3/21/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (43, 'ZSE', 'Norway', 'RE-U-A', 'Bodø', '10/5/2024', '12/10/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (44, 'OUA', 'Bangladesh', 'BF-KAD', 'Sherpur', '7/7/2024', '3/3/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (45, 'BIM', 'China', 'BS-BI', 'Yuanping', '7/13/2021', '7/16/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (46, 'MHE', 'Sweden', 'US-SD', 'Bengtsfors', '10/26/2024', '1/29/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (47, 'KTH', 'Malaysia', 'US-AK', 'Kuching', '3/3/2022', '4/22/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (48, 'PNL', 'China', 'IT-82', 'Yingmaili', '5/2/2022', '1/2/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (49, 'LED', 'Mexico', 'RU-SPE', 'San Rafael', '6/17/2024', '2/8/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (50, 'NCU', 'China', 'UZ-QR', 'Donggaocun', '6/11/2023', '10/13/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (51, 'BIR', 'Serbia', 'NP-KO', 'Smederevska Palanka', '6/19/2022', '7/1/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (52, 'NBB', 'Bolivia', 'CO-CUN', 'Yamparáez', '10/28/2023', '10/2/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (53, '0', 'Turks and Caicos Islands', 'BR-MG', 'Cockburn Town', '5/22/2024', '5/20/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (54, 'HVN', 'Russia', 'US-CT', 'Nytva', '1/9/2020', '11/6/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (55, 'HPT', 'Peru', 'US-IA', 'San Lorenzo', '7/4/2022', '5/16/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (56, 'PKK', 'Peru', 'MM-03', 'Cocachacra', '2/16/2021', '4/29/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (57, 'PGM', 'Mongolia', 'US-AK', 'Bulag', '3/21/2023', '2/17/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (58, 'MHF', 'Peru', 'CO-VAU', 'Mamara', '6/24/2024', '11/27/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (59, 'MJC', 'Philippines', 'CI-06', 'Guintubhan', '7/31/2024', '6/24/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (60, 'KSJ', 'Russia', 'GR-81', 'Sochi', '10/19/2023', '10/3/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (61, 'MXV', 'South Korea', 'MN-041', 'Yangju', '1/8/2023', '11/5/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (62, 'JYV', 'Netherlands', 'FI-LS', 'Haarlem', '3/5/2021', '6/2/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (63, 'VCR', 'China', 'VE-K', 'Zhongxi', '2/19/2022', '7/16/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (64, 'BQH', 'Greece', 'GB-ENG', 'Pátmos', '4/7/2021', '4/22/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (65, 'TQL', 'Tanzania', 'RU-YAN', 'Old Shinyanga', '5/5/2021', '7/23/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (66, 'CRZ', 'Vietnam', 'TM-L', 'Dĩ An', '1/17/2021', '2/10/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (67, 'TRC', 'Dominican Republic', 'MX-COA', 'Cotuí', '10/22/2024', '1/11/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (68, 'BSI', 'Poland', 'PH-BAS', 'Chodzież', '2/2/2020', '12/9/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (69, 'XDA', 'Colombia', 'FR-B', 'Purísima', '2/20/2020', '1/25/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (70, 'MFS', 'Indonesia', 'CO-GUV', 'Bogor', '1/19/2024', '11/10/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (71, 'MNS', 'Sweden', 'ZM-04', 'Skogås', '4/29/2024', '11/21/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (72, 'YZY', 'Peru', 'CN-62', 'Huasta', '4/13/2020', '6/3/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (73, 'PPP', 'China', 'AU-QLD', 'Huang’ao', '9/24/2021', '9/26/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (74, 'MWB', 'Portugal', 'AU-WA', 'Portel', '1/1/2021', '6/24/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (75, 'PTV', 'Indonesia', 'US-CA', 'Nggesa', '4/20/2020', '3/29/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (76, 'JOH', 'Martinique', 'ZA-EC', 'Fort-de-France', '4/5/2022', '9/18/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (77, 'BTM', 'Japan', 'US-MT', 'Usuki', '6/8/2020', '11/4/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (78, 'PHW', 'United Arab Emirates', 'ZA-NP', 'Muzayri‘', '9/21/2021', '1/17/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (79, 'RST', 'Portugal', 'US-MN', 'Pinhal Novo', '5/4/2023', '12/7/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (80, 'WSD', 'China', 'US-NM', 'Shengli', '5/3/2023', '11/22/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (81, 'BPS', 'Japan', 'BR-BA', 'Kamirenjaku', '4/17/2024', '6/29/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (82, 'HUV', 'Nigeria', 'SE-X', 'Pategi', '8/28/2023', '10/17/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (83, 'HLS', 'Brazil', 'AU-TAS', 'Buritis', '8/25/2022', '7/9/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (84, 'BCS', 'Bulgaria', 'US-LA', 'Novo Selo', '7/18/2024', '12/25/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (85, 'MOB', 'Portugal', 'US-AL', 'Vila Flor', '8/20/2022', '2/16/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (86, 'KNF', 'Madagascar', 'GB-ENG', 'Maevatanana', '5/11/2023', '1/20/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (87, 'NBH', 'Russia', 'AU-NSW', 'Trudobelikovskiy', '6/23/2023', '7/10/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (88, 'JNS', 'Tanzania', 'GL-U-A', 'Newala Kisimani', '3/24/2023', '11/8/2021');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (89, 'RAM', 'Micronesia', 'AU-NT', 'Elato', '12/4/2020', '5/8/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (90, 'RHT', 'Japan', 'CN-15', 'Chatan', '10/13/2021', '5/21/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (91, 'HSB', 'France', 'US-IL', 'Bastia', '9/26/2021', '6/16/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (92, 'AHE', 'Venezuela', 'PF-U-A', 'Tucaní', '9/12/2023', '12/8/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (93, 'RAI', 'Philippines', 'CV-S', 'Ungca', '11/16/2022', '10/5/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (94, 'GTB', 'Peru', 'MY-13', 'Huayllabamba', '2/19/2021', '6/7/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (95, 'AUE', 'Russia', 'EG-JS', 'Mamedkala', '12/12/2024', '1/24/2023');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (96, 'LKU', 'China', 'KE-700', 'Hobor', '12/20/2021', '5/12/2022');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (97, 'EVE', 'Indonesia', 'NO-18', 'Rawaapu', '12/15/2020', '9/9/2020');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (98, 'AJI', 'Brazil', 'TR-04', 'Uruçuca', '11/26/2024', '3/10/2024');
insert into airport (airport_id, airport_name, country, state, city, created_at, updated_at) values (99, '0', 'Czech Republic', 'BR-SP', 'Načeradec', '4/29/2024', '5/31/2022');